// Simple TXT export utilities for LatSpace ESG data

export const downloadTxtFile = (content: string, filename: string) => {
  const element = document.createElement('a');
  const file = new Blob([content], { type: 'text/plain' });
  element.href = URL.createObjectURL(file);
  element.download = filename;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
};

export const formatTableDataForTxt = (data: any[], title: string) => {
  let content = `${title}\n`;
  content += '='.repeat(title.length) + '\n\n';
  
  if (data.length === 0) {
    content += 'No data available\n';
    return content;
  }
  
  // Get headers from first object
  const headers = Object.keys(data[0]);
  
  // Add headers
  content += headers.join('\t') + '\n';
  content += '-'.repeat(headers.join('\t').length) + '\n';
  
  // Add data rows
  data.forEach(row => {
    const values = headers.map(header => {
      const value = row[header];
      return value !== null && value !== undefined ? String(value) : '';
    });
    content += values.join('\t') + '\n';
  });
  
  content += '\n';
  content += `Exported on: ${new Date().toLocaleString()}\n`;
  content += 'Generated by LatSpace ESG Management System\n';
  
  return content;
};

export const formatChartDataForTxt = (data: any[], title: string, xKey: string, yKey: string) => {
  let content = `${title}\n`;
  content += '='.repeat(title.length) + '\n\n';
  
  if (data.length === 0) {
    content += 'No data available\n';
    return content;
  }
  
  // Add header
  content += `${xKey}\t${yKey}\n`;
  content += '-'.repeat(`${xKey}\t${yKey}`.length) + '\n';
  
  // Add data points
  data.forEach(item => {
    const xValue = item[xKey] || '';
    const yValue = item[yKey] || '';
    content += `${xValue}\t${yValue}\n`;
  });
  
  content += '\n';
  content += `Exported on: ${new Date().toLocaleString()}\n`;
  content += 'Generated by LatSpace ESG Management System\n';
  
  return content;
};

export const formatMetricsForTxt = (metrics: any[], title: string) => {
  let content = `${title}\n`;
  content += '='.repeat(title.length) + '\n\n';
  
  metrics.forEach(metric => {
    if (metric.label && (metric.value !== null && metric.value !== undefined)) {
      const unit = metric.unit ? ` ${metric.unit}` : '';
      content += `${metric.label}: ${metric.value}${unit}\n`;
    }
  });
  
  content += '\n';
  content += `Exported on: ${new Date().toLocaleString()}\n`;
  content += 'Generated by LatSpace ESG Management System\n';
  
  return content;
};